import math
from collections import Counter

def shannon_entropy(text):
    # Count the occurrences of each character in the text
    char_count = Counter(text)
    
    # Total number of characters in the text
    total_chars = len(text)
    
    # Calculate the probability of each character
    probabilities = [char_count[char] / total_chars for char in char_count]
    
    # Calculate Shannon entropy
    entropy = -sum(p * math.log2(p) for p in probabilities)
    
    return entropy

def find_top_words_with_entropy(corpus, num_words=100):
    words = corpus.split()
    
    word_entropies = []
    for word in words:
        entropy = shannon_entropy(word)
        word_entropies.append((word, entropy))
    
    # Sort the word_entropies list based on entropy in descending order
    word_entropies.sort(key=lambda x: x[1], reverse=True)
    
    return word_entropies[:num_words]

def main():
    corpus = """
    The concept of Plug depth is present in Neon Genesis Evangelion, although precisely what it denotes is ambiguous. Since there is no indication that the interior arrays in NGE can move, "plug depth" may simply refer to the proximity of the entire entry plug to the core.

In the Rebuild continuity, plug depth designates the proximity of the entry plug's interior array to the Evangelion's core. The internal array of the entry plug, upon which the pilot is seated, can move up and down the entry plug on a track and go closer to or further from the core. The movement depends on various conditions, such as excessive synchronization or a backdoor entry into the Evangelion unit. An Evangelion entering berserker mode can also cause the internal array to drop. The violation of the acceptable safe depth purportedly threatens the humanity of the pilot. In Evangelion 2.0, three incidents involving excessive plug depth occur. Asuka Shikinami Langley's activation test puts her in close contact with the 9th Angel which results in some form of contamination, but otherwise leaves her human form intact. Mari Makinami Illustrious subjects herself to a negative plug depth when engaging Eva-02's Beast Mode through a coded back door, but emerges only with sympathetic injuries. However, upon unleashing Eva-01's inner power and moving toward the "Great Beyond Depth", Shinji Ikari transforms into a radiant being beyond physical laws. He is later said to be absorbed into the Eva.

Pen Pen (sometimes Pen-Pen or Pen²) is Misato's pet, a warm-water penguin, who lives in a second freezer she keeps in her apartment. She apparently took him with her when she left her previous job. There does not seem to be a direct real-world equivalent to the species of penguin that Pen Pen is, though the closest equivalent seems to be an Erect-Crested Penguin. Pen Pen clearly possesses retractable claws (three on each "hand"), which no living bird species actually has. He also appears to have noticeably increased intelligence: watching television, reading newspapers, taking baths in hot springs, eating human food and drinking beer, and it seems to be subtly hinted that he has a near-human understanding of events around him. All of this suggests that Pen Pen is a new species, created through advanced genetic experimentation. The manga adaptation of the series by Yoshiyuki Sadamoto (not actually set in the same continuity as the series) does provide a more in-depth explanation of Pen Pen when he is introduced. In the manga, Misato explains to Shinji that Pen Pen was created as a test animal through genetic experimentation at a research lab she used to work at. When the experiment concluded, Misato adopted Pen Pen to keep him from being euthanized. It is never stated how long Misato has had Pen Pen. A line in the first Rebuild of Evangelion movie has been mistranslated as "It feels like it's been fifteen years", although the translation should say "Such birds were much more common fifteen years ago", which gives no clue to Pen Pen's age. After Evangelion Unit-00 self-destructs and destroys a large swath of Tokyo-3, much of the city is evacuated. Misato sadly sends Pen Pen away from Tokyo-3 to make sure that he will be safe, staying with Hikari Horaki's family.

Ritsuko Akagi[2] is Nerv's chief scientist, and is in command of the Technical branch of Nerv HQ, which is responsible for the research and development of the Evangelions, as well as their maintenance and repair. She is the daughter of famous Gehirn scientist Naoko Akagi, who headed the Evangelion project before her. Ritsuko met Misato Katsuragi in college at Tokyo-2, as well as Misato's boyfriend Ryoji Kaji. After graduating college, Ritsuko joined Gehirn, and worked directly under her mother Naoko at the then-unfinished Tokyo-3. In many ways, Ritsuko is living in her mother's shadow.

Throughout the bulk of the series, Ritsuko at first appears to have a good friendship with Misato, occasionally teasing her about her smaller shortcomings. But Ritsuko also avoids speaking about the personal and emotional aspects of her own life, and under stress, the two women grow farther apart instead of confiding in each other, due to some ethical differences and Ritsuko knowing more about what is going on but refusing to share this information with Misato.

Younger Ritsuko with undyed hair, from Episode 21
Ritsuko was secretly involved in a sexual relationship with Gendo Ikari, who had been with her mother prior. In addition to "sharing" the same man, the two Akagis both manifested destructive behavior towards the figure of Rei Ayanami, despite a period of initial emotional control. In Ritsuko's case, this was clearly because of jealousy towards Rei, and it might have also been that way with Naoko. Ritsuko’s particular attack on Rei might have been triggered when she was sent in place of Rei to Seele and put nude before them. In retaliation Ritsuko destroyed the Dummy System and with it the mindless Rei clones, insisting that what she’d really killed was Rei, her "rival."

The parallels between Gendo's relationships with both Akagi women are ironic, given that Ritsuko tries to distance herself from her mother, most obviously by dying her hair blonde to be distinct from Naoko, as her natural hair color that is very similar.

Besides this, Naoko and Ritsuko appeared to have a slightly strained relationship[3]. Naoko apparently raised Ritsuko without what she felt was adequate supervision, which could be from where Ritsuko receives her tendency to shoulder all burdens and responsibilities in a tense situation, as she has been figuratively on her own for a long time.

When Neon Genesis Evangelion (1995) became a massive cultural supernova, including its 1997 theatrical alternative ending End of Evangelion, there were many attempts to ride its coat tails in terms of more adult anime. There were many attempts at an "Evangelion Killer", mecha shows which tried to follow varying from highly regarded work like RahXephon (2002) to failures like Brain Powrd (1998). The other aspect about Evangelion is that it almost became a giant flag held aloft for more unconventional and experimental anime television series to appear even if it never had any direct influence. Certainly though, between the controversies surrounding some of Evangelion's content and that, in the last half, Hideaki Anno's known personal and mental health issues were literally leading to episodes using line drawings, the fact Envangelion actually succeeded rather than crashed and burned would've allowed braver work to appear more easily if other production companies wondered if there was now a market to start creating them. Certainly experimental OVAs and theatrical films existed, but in terms of television series before Evangelion? A question to consider, mainly due to the difficult in watching every show that came before and after Evangelion to plot out a history, especially as under its shadow into the modern day, there's been many odd and bold creative works in existence even in micro-series comedies that have appeared. One of the earliest to appear immediately after Evangelion, which can be confirmed, was the cerebral sci-fi series Serial Experiments Lain, which still has a warm reputation in the West to this day.

Lain's story is incredibly relevant in the 2010s, amazingly prescient on issues we are coming to terms with about the internet and the potential existential and sociological problems with it, all in mind that whilst the internet is briefly references, this exists in a world where it's been replaced with the Navi instead of computers and its own form of the internet called the "Wired". Thankfully, this means, regardless of visual details, there's no concern of this having dated anyway since the technology already looked alien to any world and the ideas are of greater concern. It helps, from this, the series never tried to create an accurate vision of the future, instead looking at the fears and concerns of this machinery even in terms of spirituality as we follow the titular Lain, a teenage girl stuck in perpetual childishness at first and utterly computer illiterate until she and the girls in her class start getting texts from a classmate who had commit alt f4 previously. As she becomes obsessed with the Wired, head screenwriter Chiaki J. Konaka nosedives as she does into a world of philosophy, a potential God on the Wired communicating to her, and some sobering and accurate predictions on concerns we are getting to twenty plus years later from Serial Experiments Lain.

Identity theft and the obscurity the web allows? Lain finds there's an alternative version of herself online who is much bolder and even evil. Data security and personal information being compromised? Said version of Lain leads to Lain herself being accused as a peeping tom at school. Secret online groups and computer hacking? The Knights of Eastern Calculus, eerily similar to the semi-fictional organisation of expert Lisp and Scheme hackers called the Knights of the Lambda Calculus, a hacking group who will even lead people to being harmed or maimed by attacking any technology, such as traffic light systems to blurring a children's tag game with a shooter, who want to break the barrier between the "Real" World and the digital one. Existentialism and post-humanism? The idea some individuals want to evolve human beings to leave their bodies and becoming permanent consciousnesses online. Hell, throw in conspiracy theories in general too, though the only weird detail, which is weird and the only one which dates the series to back when the nineties run of The X-Files was, is where the hell the cameo by a literal green alien came from in Konaka's mind.

Lain as a series does eventually become esoteric; at first, it skims the waters of horror so much it feels like it's going to become a permanent resident, with literal phantoms haunting Lain even in the day and the telephone lines bleeding. It also emphasises how good the show was aesthetically. Now, probably the biggest surprise for me returning was that, having always been available on DVD through MVM, the original version was incredibly muddy in hindsight to the point it added to the mood, leaving the experience of seeing this thirteen episode series again on a recent restoration looking like a brand new work. Its emphasised how even on a television budget the production took its potential restrictions as an advantage, boldness in its natural look contrasting heightened colour and lighting choices. Of note too, more pertinent now in comparison to each other, the character designer is Yoshitoshi ABe, creator of the original dōjinshi of Haibane Renmei, adapted into a 2002 anime which also feels like it's in the shadow of Evangelion in terms of very creative and utterly unique animated television, a very unconventional afterlife parable with the same muted style and slow burn pace Serial Experiments Lain has1.

Again, as I've rightly remembered for years, the first few episodes feel like sci-fi horror, the images of humming electrical wires and the sense of desolate streets even in ordinary busy Japanese streets evoking what Kiyoshi Kurosawa would later go with for Pulse (2001). Contrast this with the night time scenes, with heavy neon green lighting, or the increasing influence of the computer technology through the plot, even turning into an almost bio-mechanical entity in Lain's bedroom, the floor wet in coolant, covering the entire room where once she still had plush toys everywhere. The world of the Wired is just as distinct and strange, metaphor and symbolically doing its best to perfectly imaging  an internet chatroom by representing gossiping avatars by being merely lips or eyes, or how in fear of others taking her identity, the same figures have mannequin heads of Lain on their shoulders in a darkened room in cyberspace. In knowledge that in this world, Lain herself practically enters the Wired beyond symbolic meaning, these literal visitations around unique environments are as much there to get to Chiaki J. Konaka's obsession with constantly breaking reality into pieces in most of what he writes, he both notorious and distinct in how the literal and the metaphorical are deliberately blurred in his work even for live action films like Evil Dead Trap 2 (1991); even for a children's show like Princess Tutu (2002) about ballet and fairy tales, when it gets to an inter-dimensional clockwork world where the "author" of the show exists, you can tell which episode Konaka was writing among other script writers when it's the one with the most meta and unconventional philosophy even if the target demographic was kids first.

Sound is also of importance, and not just for the inspired choice of a song by a British band on the opening credits, Bôa given a lasting cult reputation just from anime fans who had their song ] become an earworm, but on the emphasis too on sound design that crawls under the skin. It's completely comparable to Boogiepop Phantom (2000), another highly experimental show fromn this era, between them offering nuisance noise and electronic effects.

[Major Spoiler Warning]

As mentioned, this series is from Konaka, an incredibly divisive screenwriter who leads Lain to becoming difficult at points, early into the series shattering reality when even a giant deity like Lain, to her own surprise, appears up in the clouds for children to stare up to. Later episodes get into even arguments about the existence of God, an entire episode on intermingling real history of the internet and the likes of Project Xanadu with UFO conspiracy and the introduction of "Deus", a figure (Eiri) formerly human who has become a self proclaimed God of the Wired, and one episode (Infornography) whose first half if a compilation of images from previous episodes, all to represent Lain downloading an entire Navi system into her own brain, matched by a guitar riff you could grow a mullet from. Probably the biggest factor, though, which might divide viewers, is when Lain is shown not to merely by an ordinary character, who is brought into these strange events, but is part of a character arch of a unique one-off figure rediscovering her own abilities, a being (possibly through an ESP experiment talked of halfway through) capable of going beyond the Wired to actual God-like abilities. This is controversial as a plot point as, as shown in the worst examples of modern franchise blockbusters in fact, it does limit the connectability of the story from the viewer. I feel however that, especially as the first few episodes feel random, the narrowing of the narrative not only helps the show and but, as it focuses on specific characters, the real virtue of the characterisation appears.

[Spoilers End]

Another thing I forgot, for all its esoteric and eerie shenanigans, was how emotional the show eventually is. Here I admit, for its entire cool atmosphere, and general sense of complete strangeness, actually the real virtue turns out to be the bitter-sweet tale of Lain trying to find happiness. Only close to Alice Mizuki, a school friend, her isolation in the world and how attempt to grow on the Wired (literally) is fraught with further isolation, here a tale which does anchor the entire series with a greater meaning. All the philosophy is weighted ultimately by how as much it connects to her too, evoked when rather than the usual opening before the credits (a male voice over text) she opens the final episode talking directly to us about whether she actually exists or not. All the eccentricities are softened by how utterly emotional the show finally is within the final scenes.

This means Serial Experiments Lain earns its pretensions. Chiaki J. Konaka is notorious for his clear hatred for conventional linear storytelling, but there is so much about the dangers of the physical world against the digital one which have become ever more salient. It also makes sure the characters are of interest around Lain too. Her family, very disconnected, are so for a reason and builds itself to one single scene of emotional resonance; even two men in black, with cybernetic eyeglasses which stalk outside her house, get personalities and enough humanity to why they are there that their fate as everything turns pear shape is significant. That's ultimately, upon returning to this show, why I still love Serial Experiments Lain.

I once, on the first viewing, dismissed it with the same misguidedness I dismissed Boogiepop Phantom, another of these bold and innovative works from under the shadow of Neon Genesis Evangelion. Second time, many years later, it was the surreal and unconventional tone, on the borderline to horror and sci-fi, completely introspective and psychological, which won out. Now, this is in mind still but the drama is all what's left at the end and actually touching in the end. Certainly for me, when you start most series, you should hope for a progression where the final episode is that you'd never expect it to end as from just the first episode, said progression felt throughout natural or at least an escalation in drama, emotional and/or spectracle. Certainly, with Lain this is as good as you could get with this natural progression.

Not a lot of my readers are anime fans, but I felt like revisiting one of my first--and favorite--anime series and explaining what made this series so good. Serial Experiments Lain has been largely forgotten to anime history, and I felt it necessary to explore what it had to say about technology, and the ways it got the Internet right 17 years ago, at a time when so many cyberpunk/technologically-focused stories (like this, for example), got technology so wrong.

Serial Experiments Lain is a 13-episode series that centers around a young, socially isolated 14-year-old girl who receives an email from a classmate who committed alt f4, urging her to follow in her footsteps and live in the "Wired" (the Internet). Intrigued by this email, Lain asks her father, who works at the Tachibana Labs computer company and is himself an early adopter/power user/tinkerer, who is excited to take her under his wing, to upgrade her computer. Lain uses a "NAVI", which is based on a variety of Apple products (the artists working on the series at the time loved Apple), but I find that the top-of-the-line model resembles more of a cyberdeck than a traditional desktop computer. It isn't long before we see Lain switching out parts, and her setup grows immensely throughout the series.

There are some important things to note in episode one: The shadows in the series are colored, and this is deliberate. The shadows represent the world of the Wired, underpinning Lain's "reality." The buzzing of the power lines in the beginning episodes eventually become distinct, though muffled speech, delineating Lain's ignorance of the Wired to her power over it. During her commute to school, we get a very eerie scene where the power lines start to bleed. Others have said that this represents Chisa's alt f4, but I don't think that's accurate: It is foreshadowing the central theme of the series, that is the Wired and the "Real World" becoming one and the same, as we shall see.

One of the most interesting comparisons to make here is between Lain and The Matrix, specifically The Animatrix and the second film. In "Kid's Story," a teenager is contacted by Neo and commits alt f4 by jumping from his apartment building with the goal of reaching the Real World. A great deal of effort is made by Lain's classmates and another character to convince Lain to kill herself and enter the Wired. It's worth noting here that Lain came out in 1998, The Matrix came out in 1999, and The Animatrix after that. I have no doubt that the Wachowskis saw Serial Experiments Lain.

The Knights of the Eastern Calculus

In Layer 03, Lain receives a chip called a "Pachuke," and inquires at the rave about its function and manufacture. Taro, one of the kids who hangs out at the club, informs her that the chip was manufactured by the Knights and is extremely rare, bestowing powers and privileges to its user well beyond that of normal denizens of the Wired. The Knights are one of the most intriguing things about the series, as they are an anonymous group of hackers/renegades who seek to govern the Wired and are responsible for a deadly computer game. Few people know who the Knights are, and few people familiar with the series quite understand the brilliance of their existence in the series. Watching SEL in 2015, it is quite obvious that the Knights are analogous to another [A]nonymous hacker collective. SEL deserves some serious credit for its predictions, and its accuracy well beyond its time. In the series, the Knights have spliced a dungeoncrawling survival game not unlike many horror games seen today (think Slender: The Eight Pages) with a scientific experiment that sought to harness latent psychic energy from children called the Kensington Experiment, presided over by Professor Hodgson. The experiment was terminated because all of the children involved in the experiment died. Professor Hodgson explains to Lain that he sought to destroy all of the material involved in the experiment, but someone "dug it out of the trash" and incorporated it into the game (Episode 6)

This hybrid allowed other players to play as the monster, and any player who loses in the game dies in real life. The Knights are also able to use the technology in their game (called PHANTOMa) to kill other users. A housewife orders a Knights-manufactured PCI card and uses it to kill a person walking in the street wearing a headset and mobile wifi gear. Later, we find this same card, fried, in the garbage. In one scene, also in episode 6, after Lain discovers what the Knights did, she verbally abuses them by calling them trolls. They retaliate by--I think--uploading malware to her computer that causes her coolants to fail and her system to explode, which would have killed her had she not left her room. On top of all that, the Knights are also propping up a second alt f4-turned-digital-consciousness named Masami Eiri.

Masami Eiri was an employee at Tachibana Labs, and he was tasked with creating IPv7 (Protocol 7; we are currently on IPv6). He included bizarre conspiracy theories involving psychic research and electromagnetic fields into his construction of the protocol, and aimed to insert himself into the Wired as its god. He wanted to move all of humanity from the Real World into the Wired, and allow people to communicate seamlessly, "without devices." The best comparison I can make for this is to the Human Instrumentality Project in Evangelion, which was also aimed at merging human consciousnesses beyond that of the flesh, albeit for religious reasons. When Eiri's managers discovered this, they fired him immediately, and he killed himself by running in front of a train. His consciousness lived on in the Wired, where he did become a god, thanks to his believers: The Knights. Eiri also claims responsibility for creating Lain. Eiri himself became god, basically, by using memes perpetuated by the Knights (think, for example, imageboard or lame sites), and he lives on simply because people believe in him (similar to American Gods, where belief gives power). This is the same reason why aliens appear in the series: Because urban legends (Roswell, mentioned in episode 9, for example) become "fact" through collective belief in conspiracy theories (TVTropes.org notes that the alien who appears as Lain's avatar in Alice's room in Episode 11 is wearing a Freddy Krueger sweater). Episode 9 opens with the line, "For now, conjecture has become fact, and rumor has become history." While I am aware that The X-Files also heavily dealt with conspiracy theories around the same period, it did not address the way that these theories proliferated in real life through the Internet the way Lain did. In fact, I would argue that the very reason why they are discussed at all in SEL is because of how the Internet gave them a way to propagate freely in the underbelly of the Web, treating them as an artifact of belief, instead of addressing the possibility outright that aliens could be real. It's less "The truth is out there" and more "The expansion of the Internet has created a seedbed for all kind of crazy stuff!" Again, this series came out in 1998, and this is 2015, when conspiracy theories thrive on the Internet and have leaked into real political discourse.

Who are the Men in Black (not Will Smith and TLJ)?

The Men in Black are two mysterious figures who at first have an ominous presence as they stalk Lain from a black car, but they are not there to hurt her. At first, she suspects that they are working for the Knights, but the Men in Black are there simply to spy on her for an unnamed employer. They suspect that Lain is the Lain of the Wired (the "evil" one), and  later, when they take her in, they discover that she is, and reveal that they do not want the Wired and the Real World to merge. However, they are ordered to back off by their employer, and only resurface after Lain publishes the list of Knights members, whom they assassinate. In Layer 12, the Men in Black are betrayed by their employer and killed by an avatar of Lain (ostensibly with the same technology as the Knights with PHANTOMa). It turns out that their employer was in contact with Eiri, which may be why Lain killed them.

What happened to Alice, and why does Lain have three personalities? 

Alice is Lain's best friend, and her story arc is both depressing and slightly unclear. But first, we must explain Lain's three personalities. Lain in the real world is socially isolated, quiet, and generally passive. She discovers, as people recognize her in the club in episode 2, that there already exists a Lain in the Wired. This version of her is evil, and has spread embarrassing information about Alice, specifically, that she has been sleeping with one of her teachers. This is devastating to her (obviously), and is a major impetus for Lain's actions later in the series. It's worth noting that this is something SEL gets exactly right: That information on the Internet (The "Wired" in the show) can be found and used against people in the real world, with real consequences. On the Wired, Lain (the persona that the Real Lain has adopted for herself on the Wired) is assertive, belligerent, and quick to verbally attack other users, which reflects current reality: Many socially isolated people adopt a more forceful personality on the Internet.

It is also possible that Eiri had dummy copies of Lain on the Wired without her knowledge. "You wanted to pass off these dupes as me!?" (Episode 8)

In episode 12, when Lain is about to give in to Eiri and Chisa's demand that she forfeit her physical form and live in the Wired as a disembodied consciousness, Alice shows her the value of a physical body by letting Lain feel her heart beat. In fact, it is Alice who comes to her aid at the end of the series and saves her from making the same mistake Eiri and Chisa made. Here, Lain also discovers how much she had hurt Alice, and this is what causes her to hit RESET.

So what does Lain do? How does she become a god?

In order to save Alice from the consequences of what the Evil Lain did, she erases everyone else's memory of Alice's sexual indiscretion, but does not erase Alice's own memory of her humiliation. Lain decides--after seeing the pain that her actions caused her only friend--to erase everyone's memories of herself, effectively erasing her own existence. The power she gained in the Wired and her need for a physical body (she did not kill herself) allows her to become what Eiri could not, and instead of fulfilling her stated purpose (according to Eiri), she reestablishes the barrier between the Wired and the Real World. Many of the people she knew and loved could almost remember her. Alice, seen with her fiancee, struggles and fails to remember that Lain was her best friend. 
Is Lain a computer program? What happened to Mika? And why is her family fake?

Eiri claims--late in the series--that he is responsible for creating Lain. She is, in his words, "an executable program with a body." Her entire life is a plant, and this knowledge is what pushes her over the edge. However, Eiri also says that all other people are "applications," so he is not exactly to be trusted. Considering Mika's fate, it may be more accurate to say that the Knights are responsible for Lain's existence, not Eiri.

Mika was a disaffected, "mature" teen who had very little interest in Lain. Because of her marked disinterest, the Knights manipulated her surroundings, telling her to "Fulfill the prophecy!!!" and drove her insane. There are theories on the Internet (on our Internet) that say that the Knights wiped her mind, but I think this goes a bit far. It is sufficient to say that she had a severe mental breakdown and was incapacitated for the rest of the series.

Her mother at one point--who expresses the same disinterest as Mika and yet suffers no consequences--remarks to her husband/Lain's father that "We don't have much time" (or something to that effect) as the two of them initiate intimacy. 

The bizarre thing about her family being faked is that when we see them again in episode 13, they are still together, only with Lain missing. This is bizarre because, after Lain hits the reset button, Masami Eiri is still employed, the Men in Black are construction workers, Chisa (the alt f4 from the beginning, and the one who originally sends Lain down the rabbit hole) is still alive. and other characters are similarly changed. The only explanation for this is that her parents would have fallen in love anyway, making at least some of the prophecy less impactful. 

I only have one major question: If Eiri is truly responsible for creating Lain, why does he not realize that Lain is supposed to overtake him as god? Or, as the title of episode 12 suggests, Eiri is so consumed by his own ego that he still thinks he can be god? Even in the denouement, Masami Eiri suffers delusions of grandeur...

SEL  was released in 1998, and I find it amazing, watching it 17 years later, how prescient it was. A lot of what is happening now is seen in the series, from Anonymous, lame sites/imageboard, TOR/the "Dark Web," doxxing, conspiracy theories (though they've been around for a lot longer than the Internet, their swift proliferation is what makes SEL so relevant), and the consequences of the collapse of the barrier between the Real World and the Wired. Transhumanists are considering the implications of uploading human consciousness to a computer network, and we are on the verge of VR. We are working on accessing the Internet without any devices. These are topics that are explored on shows like Black Mirror today, but Serial Experiments Lain discussed them way back in 1998. I would also like to point out that the main character is a girl, whereas in 2015, most people who are computer experts (those who work in Silicon Valley) are men. At the time SEL was made, women were much more involved with computers. I love that Lain focuses primarily on tech-savvy girls.

SEL is a perfect expression of the anxieties felt at the dawn of the Internet age, during the dial-up era, and remains a landmark achievement in cyberpunk and science fiction generally.

"This afternoon, the firewall of the Information Bureau's Information Control Center was cracked by some unnamed renegade party. As a result, the Information Network System of the Wired is in total disarray. And furthermore, be advised that although it is actually a live broadcast and is being sent out at this very moment, it is quite possible that it may arrive tomorrow, right now, or perhaps yesterday."

As I talk to my friends about Lain, because they recently watched it for the first time, or haven't seen it in a long time, I keep thinking about how great it is. It eats at my brain the way that only Neon Genesis Evangelion could, and while Evangelion was excellent, very little of it had to do with the real world; all of the religious references kind of went nowhere, and somewhere along the way in my mind, SEL's unwavering allegiance to reality--to such a degree that few other science fiction stories ever match--causes me to fall in love with it over and over again. I keep thinking about that one character in episode 7, who was wandering the busy street with his backpack and VR gear. We can do that now. Yes, VR has been a thing for a long time (think Star Trek's Holodeck), but few have ever imagined how it might work in reality. I am stunned by the fact that SEL came out 17 years ago, and almost everything it ever said about technology and society is actually true.

I can hardly believe that the series ever got made in the first place. It had a shoestring budget, there is no official merchandise (except for a Japan-only one-shot manga and a Japan-only PSX adventure game), and the animation doesn't look too good (and that's putting it nicely). 

And yet it is the best anime I have ever seen. I first saw it when I was in high school, and it was, if I remember correctly, the first anime series I ever purchased (my first anime purchases were AKIRA, Ghost in the Shell, Perfect Blue, and Serial Experiments Lain). Lain is the only anime I own on Blu Ray, and I purchased it soon after I watched it again for this essay. My only complaint with the Blu Ray is that there aren't enough extras about Lain: No interviews, concept art, etc. I had to dig up an interview with the creator in a French magazine (that interview and others can be found here) to try to figure out where it came from, and I still don't know. 

The only thing I do know is that I want to watch it yet again.

Out of all the “post-Evangelion” anime to be released, Serial Experiments Lain is surely the most successful television series. It manages to surpass Neon Genesis Evangelion in its intellectual coherence and thematic development, and succeeds in conveying very similar messages about the necessity of physical human contact. The haphazard, raw brilliance of Hideaki Anno’s Evangelion has its peculiar charms, but this cool, crafted series by Ryutaro Nakamura succeeds on a different level. Anno is a master of bringing naked psychological exposure to a visual medium and startled an anime fanbase accustomed to stock characters, cliche plots, and commercial exploitation. Evangelion’s visual storytelling innovations and emotional intensity were rightly considered a necessary shock to the system, and Lain most likely would never have been created had Evangelion not been a huge success. Many imitators of the show followed in its wake, and indeed, most of the “artsy” and avant-garde directing techniques here are borrowed from Anno’s visual vocabulary –periodic flashing of text, bizarre still shots on inanimate objects, interior monologues, and Eisensteinian montage. But the ends to which Nakamura brings these techniques in Lain deserve a close look from a philosophical and theological standpoint, which cannot be said for the ultimately irrelevant Christian/Jewish symbolism of Evangelion. Anno’s work is almost wholly psychological; Nakamura’s work, by contrast, is not only psychological but genuinely intellectual and by its conclusion, nearly spiritual.

The animation quality is high, though minimalistic in the vein of Evangelion’s latter half, filled with still-pans and little background motion. The soundtrack, too, is minimal, cued similarly to the films of Stanley Kubrick, David Lynch, and The X-Files; indeed, the conspiratorial noir atmosphere is very remniscent of the best of that TV program. For this viewing, I watched the English dub, which is above average, though it lurches occasionally into melodrama when the scene demands emotional restraint. Of course what stands out are the Evangelion-inspired directorial techniques, but this time they feel more purposeful in conveying the blurry lines between the real and Wired world. Little in this show seems spontaneous or random, a sense that was confirmed in this viewing (this is the second time I have watched the series). It lacks Evangelion’s emotional intensity and abject sense of existential despair, and is not character-oriented as such. That may not be a weakness, however, as the primary focus of this show is upon the ideas. It is a marvelous idea-oriented program, one of the few examples of television that actually challenges the mind rather than dulling it. It rightly won a Japanese Ministry of Culture prize for excellence, and will undoubtedly be regarded as a modern classic of intellectual exploration.

(WARNING: SPOILERS AHEAD)
This is certainly an anime series that discussion alone will not exhaust. There are many interesting philosophical and spiritual ideas floating about, but the dominant theme is that of immaterial versus material existence. Or, in other words, human life without and with a body. If, as the Wired “God” and his followers claim, human beings are more advanced in their evolution when they shed their body-shells, why shouldn’t we all just join together as one in the Wired? Why don’t we all form a large collective unconscious, an Emersonian Oversoul, residing in Nirvana? The idea is extremely similar to the Human Instrumentality Project of Evangelion, where the secret committee plotted to join all human beings together by dissolving their bodies into soup and thus ensure that no individual soul would ever be alone again. Historically, it certainly resembles the tenets of Buddhism in which material existence is an illusion, as well as Platonic Gnosticism, where the flesh is seen as wholly corrupt and salvation found by living a purely spiritual experience.

Standing against this view in Lain is that bodies, human memories, the stuff of daily existence, are essential to who we are as human beings. At the center of this struggle is Lain, the girl created by Tachibana Labs in order to bridge the gap between the Wired and the physical (“real”) world. She was created to fight Masami Eiri, the self-proclaimed “God of the Wired” who wanted to join all human beings into disembodied souls in the Wired. As a result, she has existence both in the “real” world and in the Wired world, though she was first created in the Wired by her “father.” Her search for identity and for the essence of human existence fuels the show’s plot, and by the show’s conclusion, Eiri’s solution to isolation and human loneliness has been decisively rejected. This is a show that ultimately celebrates and affirms the need for such things as heartbeats, touch, flesh, and physical connection. In that sense it is quite compatible with the Christian view of humanity, contra the Gnostic view: it affirms that flesh is fundamentally not a bothersome shell to be shed, as so many cultists East and West have long claimed. We are both flesh and spirit. Even the Bible says that we will have resurrected bodies; we will not simply be souls flitting about like ghosts in heaven or hell. It is ultimately Lain who overcomes the false God and who ensures that the real world cannot spill over into the Wired, and vice versa, thus guaranteeing the safety of physical human existence. She is only able to do it be ceasing to exist in the memories of every human being around the world. In some sense, she is a Messianic figure in the show. There are even a false Lain (anti-Lain?) in the Wired, created by the false God’s followers the Knights, used to mislead people into being sucked into the Wired permanently. At first Lain is confused about this other version of her, but she comes to realize who she is and, through the love of her friend Alice, becomes sure of “the one truth” in the world: that love, memory, and the true God are what sustain human existence.

There are two significant subtexts in this show as well; one deals with post-modern social isolation, and the other deals with the effects of technology on human nature. I found the first subplot to be the most compelling, the emotional “hook” of this story. Lain is a girl who in the real world is normally ignored. There is a strong temptation for someone like her to become absorbed into the online world of the Wired and become a Somebody there, wholly absorbed. Indeed, those who commit alt f4 in order to give up their bodies are usually social outcasts or otherwise outsiders. As Lain comes to realize that she hardly matters to her “parents,” or “sister,” or most of her classmates, she begins to succumb to the lie that Eiri is her creator and that the only way to free herself is to get rid of her human body. It is only the love of a wonderful friend, Alice, who helps her realize that being alive is real. The most affecting scene of the series takes place when Lain, almost wholly taken in by false God Eiri, is slipping away from human existence. Alice puts Lain’s hand over her heart, and her hand over Lain’s heart. Together they recite, “Heartbeat–thump. Thump. Thump. Thump.” A more effective presentation of the value of life is hard to imagine.

There is another temptation that Lain faces besides the shedding of her physical form. As a powerful software program in the Wired, Lain is able to manipulate and even erase the memories of others–memories of herself. When the anti-Lain causes havoc and hurt to many people, including Alice, and Lain fails to persuade anyone that she and the anti-Lain are not one and the same, she decides that the only way to undo the hurt is to erase everyone’s memory. One of the more interesting postulates in the show is that human beings only exist when they are remembered by others. So by erasing herself from the Wired and from people’s memory, she is ceasing to exist, and thus undoing all the damage and hurt caused by the false Lain and the false God that was using her. This saves humanity, but then, where is Lain? Does she really exist? The final episode details how the world might be if she had never lived, and all seems well; the boundary between the real and Wired world is clear.

And yet. And yet . . . . Lain is still aware of herself. Why? Why does she still continue to “exist” when she does not in fact exist in the real world any longer? The final temptation is for her to regard herself as a Goddess, to become a watcher in the Wired looking over the real world, but with no substance. But Lain still does not understand why she continues to exist . . . .

Then, a heavenly vision appears in the sky. It is an image of her father, the one who pretended to be her biological father but in fact is her true creator. He remembers her. He helps her realize, too, that memories can never be completely erased–in the world where she does exist, her father and Alice feel something strangely missing that they can’t quite place. As a result, she can still continue to have existence in a human body and as a spirit on the Wired. The theological implications of this are clear. Human beings exist not only in the memories of others. Even if everyone were to forget them, they can still exist because they are remembered by their Creator. Lain thus overturns one of the cornerstones of modern philosophy, Descartes’ cogito ergo sum. Descartes was only sure of his existence by the fact that he was self-aware. Lain proposes that instead, our existence is only sure because we are remembered not just by others, but ultimately by our creator, our Heavenly Father. Our self-awareness is insufficient. Only because we are held in the true God’s awareness can we exist. This is explicated quite literally at the show’s end.

Lain isn’t a Christian show in any proper sense of the word, but it is actually much moreso than the symbol-drenched Neon Genesis Evangelion. While it does indulge in ideas drawn from Carl Jung about the collective human unconscious, the fundamental view of existence and humanity it promotes is compatible with the Christian affirmation of the physical creation, and even smuggles in an alternative ontology that is ultimately can be interpreted as theocentric. Quite an accomplishment for any anime series, certainly, but in the scant world of good TV entertainment this certainly qualifies as some of the most profound thinking about human nature to date.

Black Lady was the form Chibiusa took when she was turned to evil by Wiseman.

In the manga, Chibiusa accidentally dropped her Time Key and wandered into the Fourth Dimension. When she became lost and scared, she decided to return but found she no longer had her Key. Wiseman confronted her and lured her to him preying on her loneliness. She took on her new form as Black Lady and gave the future Silver Crystal to Wiseman - though he was unable to use it. Mamoru had followed Chibiusa into the storm in the Fourth Dimension and he became trapped in the spell of the Black Moon as well.

It was Black Lady that called forth the true form of Wiseman, the planet Nemesis, then commanded Mamoru, now under the power of the Dark Moon, to take Sailor Moon 's brooch and Silver Crystal of the 20th century. Prince Dimande took the crystals from Black Lady and planned to touch them together, resulting in the destruction of everything. However, Sailor Pluto used her forbidden power Time Stop to keep the crystals from coming in contact. Because this was taboo, she died. Seeing Pluto die caused Black Lady to remember who she truly was and awakened her powers as a Sailor Senshi, Sailor Chibi Moon.

In the anime, Chibiusa travelled to the future with the Sailor Senshi and once there, heard King Endymion tell them that the Silver Crystal disappeared shortly before the Black Moon Clan attacked. Thinking that it was her fault that the Crystal vanished, and thus her mother was hurt, she became upset and ran away, leaving the shield around the Crystal Palace. Wiseman found her there and began showing her illusions that made her think that everyone blamed her for what happened. He told her that he could convince everyone that it was not her fault, and by taking advantage of her emotional weakness, used his power to transform her into Black Lady.

The first time Sailor Moon encountered Black Lady, she tried to use the Silver Crystal to turn her back; it almost worked, but Wiseman appeared in time and persuaded her that her memories were not real and her friends and family did not really care about her. When Sailor Moon tried again later, Black Lady deflected the Silver Crystal's power and was unaffected by it.

In their final battle, Black Lady attacked Sailor Moon, but Tuxedo Mask protected her and took the blast. Black Lady was stunned by this selfless act, and the Senshi tried to convince her of their love for her. Wiseman attacked in an attempt to stop them, but Sailor Moon managed to use the power of the Silver Crystal to transform into Neo-Queen Serenity, her future self. Sailor Moon and Tuxedo Mask together overcame Wiseman's power and convinced Black Lady to transform back to Chibiusa.

When Sailor Moon fans first saw Mini Moon literally fall from the sky in front of Sailor Moon and Tuxedo Mask, they had no idea who or what this character was. But one thing was certain: she was most definitely related to them. Fans later discovered that Mini Moon was their daughter from the future and came from a place called Crystal Tokyo, a utopian world that was now under attack by the Black Moon Clan. And Chibiusa needed help in waking her future mother, Queen Serenity, so that her world could become better then.

Things did not go according to plan. When Mini Moon ran back to the future, with the Sailor Scouts right behind her, she fell under the spell of a villain only known as Wiseman, a mysterious cloaked figure that had the power to take Mini Moon's greatest fears and insecurities and turn them against her. This turned her into Black Lady, an older and more evil version of herself. As Black Lady, Mini Moon became part of the Black Moon Clan, which made her an enemy of her family and the Sailor Scouts.

Although Black Lady only survived a short time, there is still a lot that only hardcore fans really know about her.

When the surface of the planet becomes too dangerous, Black Lady places Prince Demande and Saphir in the Darkness Chamber together. When Wiseman calls for her, Black Lady takes Prince Demande and Saphir through a controlled space to the Castle of Darkness. When Saphir inquires to the whereabouts of Rubeus, Black Lady informs him that Wiseman had to kill Rubeus because he rebelled and attempted to escape and he deserved it.

Black Lady presents Prince Demande and Saphir with more powerful black crystal earrings each. Black Lady sends them to make preparations to send another Malefic Black Crystal monolith to earth.

When Black Lady enters the Crystal Palace to see Neo-Queen Serenity, King Endymion is shocked to see his daughter all grown up. When Sailor Moon follows Luna-P to the Crystal Palace, Black Lady goes to grab her Crystal Star but is exiled from the Palace by Neo-Queen Serenity's power and lands outside. Black Lady realises she is evil now therefore she is unworthy of being inside the Crystal Palace.

When Sailor Moon, King Endymion, Sailor Mercury, Sailor Mars, Sailor Jupiter and Sailor Venus gather outside where Black Lady landed, she summons Wiseman. Black Lady explains she used to be known as Chibiusa now she is Black Lady, the Queen of Darkness.

Black Lady summons Prince Demande and Saphir. After Prince Demande uses his Invincible Evil Sight to immobilise Sailor Mercury, Sailor Mars, Sailor Jupiter and Sailor Venus, Black Lady tosses them aside. Black Lady instructs Tuxedo Mask to make Sailor Moon suffer. Black Lady blasts Sailor Moon before bringing a third Malefic Black Crystal monolith to earth. When Prince Demande reveals that he was never under Wiseman's mind control spell, Black Lady orders Saphir to kill his brother.

Black Lady orders Tuxedo Mask to take the Silver Crystal from Sailor Moon. Black Lady snatches the Crystal Star from Tuxedo Mask, opens it and removes the Silver Crystal. She holds a Silver Crystal in each hand, then Prince Demande snatches them from her and threatens to bring the two crystals together.

Just as Prince Demande is about to bring the two crystals together, Black Lady helpless to stop him, Sailor Pluto commands time to stop. When Black Lady is released from the time freeze she witnesses the others grieve over the loss of Sailor Pluto. Distraught over the death of her closest and dearest friend, Black Lady's crystal earrings shatter and she is transformed back into Chibiusa than for the first time, Sailor Chibi Moon.

Act 2 - After transforming for the very first time, Sailor Mercury uses her attack Mercury Aqua Mist on the enemy Youma, the Female Instructor.

Act 3 - Sailor Mercury teleports to Sailor Moon's location, where Jadeite introduces himself. She uses her Aqua Mist on him and Jadeite retaliates by freezing Sailor Moon and Sailor Mercury so he can bring them to Queen Metaria. 

Act 4 - Sailor Mercury and Sailor Mars hold off the possessed Princess D so she doesn't escape with the treasure.  

All four Kings of the Dark Kingdom known as the Shitennou appear and introduce themselves as servants of the Great Ruler. Kunzite, Zoisite, Nephrite and Jadeite inform the Sailor Guardians they want the Silver Crystal for their Great Ruler. As Princess D recovers, the Sailor Guardians flee. 

Act 5 - When Sailor Moon, Sailor Mercury and Sailor Mars have transformed, Bride uses an energy blast on them which compromises their ability to see. Bride strikes down the three Sailor Guardians with a green energy blast and Makoto Kino tosses the Bride over her shoulder.

After the completion of the battle, Luna appears in front of the now four Sailor Guardians and presents Sailor Moon with the Moon Stick.

Act 6 - Sailor Mercury, Sailor Mars and Sailor Jupiter battle Zoisite, demanding he return the energy he has stolen for the Dark Kingdom. Zoisite retaliates with a blast of energy, and they lay on the ground helpless.

Act 7 - When Sailor Mercury, Sailor Mars and Sailor Jupiter arrive Zoisite has a hold of Sailor Moon from behind by the neck. Sailor Mercury uses her Aqua Mist in conjunction with Mars' Akuryo Taisan and Jupiter's Supreme Thunder but Zoisite blocks and reflects the energy back at them, knocking all three to the ground.

Act 8 - Sailor Moon, Sailor Mercury, Sailor Mars and Sailor Jupiter arrive to help Sailor Venus fight Kunzite. Sailor Mercury let's Sailor Venus know, they were all alone in the beginning. She uses her Aqua Mist against Kunzite but her attack bounces off his protective shield.

Act 9 - Sailor Mercury watches in disbelief as Sailor Moon transforms into Princess Serenity. A tear falls from Serenity and turns into the Silver Crystal, the light it emits is so bright it is almost blinding that Sailor Mercury doesn't see the light enter Tuxedo Mask's body. When Queen Beryl arrives for the Silver Crystal the Inner Senshi protect Serenity and Tuxedo Mask from Kunzite. She uses her Aqua Mist. Distracted while fighting Kunzite snatches Tuxedo Mask and takes him back to the Dark Kingdom.

After the power is restored Sailor Venus, Sailor Mercury, Sailor Mars and Sailor Jupiter take their distraught Princess back to headquarters where Sailor Venus reveals the truth. As Artemis tells his story, Sailor Mercury begins to remember her past life during the Silver Millennium.

Act 10 - The Sailor Guardians hold hands in the fountain and teleport with Luna to the moon inside a shield they create. They land at 'Mare Serenitatis' aka 'The Sea of Serenity' and notice the moon is dark and quiet. They walk amongst the ruins of the Moon Castle to the Chamber of Prayer where only Queen Serenity herself was allowed to enter. Sailor Moon spots a sword in stone, Sailor Jupiter tries to pull it out. With Sailor Mercury and Sailor Mars help they manage to loosen the sword from the stone slightly before Sailor Venus completely frees the sword. Queen Serenity's consciousness appears to the Sailor Guardians and as she tells them the history of the Moon Kingdom their memories return and they see the Moon Kingdom as it once was. The Sailor Guardians head back to Earth just as morning arrives.

When Kunzite begins transforming Tokyo into a desert of ice, the Sailor Guardians arrive. Sailor Moon inquires to the whereabouts of Tuxedo Mask but Kunzite notices the Silver Crystal around her neck and goes to attack her but the Inner Senshi block the attack. Sailor Mercury fights one on one to protect the Princess and the Silver Crystal with Zoisite. Sailor Venus explains that the Shitennou are not their true enemies, Sailor Mercury remembers one day when Princess Serenity snuck out to see Prince Endymion the Inner Senshi followed her, and she too was fascinated with Earth and feel in love. When the Shitennou attack the Inner Senshi, Sailor Moon retaliates by throwing her tiara at the Shitennou. The Inner Senshi combine their power together and use Sailor Planet Attack against Shitennou in order for them to recall their true selves but before the Shitennou can regain their memories they teleport away.

Act 11 - When Motoki Furuhata grabs the Silver Crystal from Usagi, Sailor Venus uses her Venus Love-Me Chain to snatch the Crystal back but Tuxedo Mask blasts energy and floats the Crystal then Sailor Mercury uses her Aqua Mist to blow the Crystal towards her but Tuxedo Mask grabs it so Sailor Mars kicks him.

Act 12 - The Inner Senshi block an attack from Tuxedo Mask. When Artemis notices HQ is starting to collapse, Sailor Mercury creates Hyperspatial Sphere Generate which teleports Sailor Moon, Sailor Mercury, Sailor Mars, Sailor Jupiter, Sailor Venus, Queen Beryl and Tuxedo Mask out of HQ. Beryl clutches all five Sailor Guardians with her hair. Sailor Venus summons the Sacred Sword to her hand and uses it to cut the Guardians free from Beryls grasp. Sailor Moon takes the Sacred Sword, Sailor Mercury uses Mercury Goggle to find the weak point, Sailor Venus uses her Love-Me Chain, Sailor Mars uses her Akuryo Taisan and as a team the Sailor Guardians attack Queen Beryl.

The Inner Senshi fly to the North Pole when Luna and Artemis detect Sailor Moons location. When they enter a cave they come across the more powerful then before Shitennou and have no choice but battle with them. When the Inner Senshi use their Sailor Planet Attack against them, the Shitennou remember their past lives as Knights who swore to protect their master Prince Endymion. When Queen Metalia destroys the Shitennou for rejecting the power of darkness the girls begin to grieve until they hear the voices of the Knights telling the Inner Senshi they still have a mission to complete and Sailor Moon needs help.

Sailor Moon picks up the Sacred Sword just as the Inner Senshi arrive. Seeing what Sailor Moon is about to do, they voice their opinion against it. 

Act 13 - The Inner Senshi watch as Sailor Moon strikes Tuxedo Mask with the Sacred Sword before turning it on herself and they fall to the ground. Queen Metaria attacks the Inner Senshi as she is filled with the power from the Silver Crystal. When Sailor Moon is sucked into Queen Metaria along with Tuxedo Mask and the Silver Crystal, the Inner Senshi teleport from the Dark Kingdom to the Arctic Circle which is now just a field of stone. They use Sailor Planet Attack against Queen Metaria which she uses against them. The Inner Senshi lie on the ground helpless to stop the invincible Queen Metaria. They remember Usagi's smile, her strength and hear her words of encouragement and they know Sailor Moon is still alive. The Inner Senshi lack the strength to seal Queen Metaria and her darkness themselves but they can make the conditions right to give Sailor Moon the chance by using the power of their individual guardian planets and the energy generated when they transform. They throw their transformation pens, which is the same as throwing away their lives. Pens are not just for transformation they contain sacred powers each Guardians very life force, send them to Sailor Moon to help her by making the ultimate sacrifice. To awaken their Princess, Sailor Mercury calls out "Mercury Power" and throws her pen into Queen Metaria who attacks the Inner Senshi.  

Act 14 - Still believing that Sailor Moon can destroy Queen Metaria, the Inner Senshi lend Sailor Moon their strength. Their transformation pens glow and transport all their power into the Sacred Sword. The sword transmits all the energy to the moon and the tower begins to regenerate.

Chibiusa Tsukino is the Crown Princess of the 30th century kingdom of the Moon, Crystal Tokyo.

She is the first princess of the Silver Millennium known as Small Lady by the Sailor Senshi of the future. The Black Moon Clan call her Rabbit. She travelled through time so she could save her mother. She is really good at the Sailor V game.

Act 14 - Chibiusa falls from the sky through a time portal and lands on the back of Usagi's neck and kisses Mamoru Chiba on the mouth in the process. She introduces herself as "Usagi Tsukino" and asks Usagi why she has the same hairstyle and the same name as her. Realising that she's found the person she's looking for, Chibiusa pulls out a gun and threatens Usagi to give her the Silver Crystal or she'll shoot.

Act 15 - Mamoru grabs Chibiusa just as the toy gun goes off and Usagi falls to the ground, Chibiusa runs off. Usagi and Mamoru find Chibiusa in a park sitting on a swing. When he takes Chibiusa's hand, Mamoru receives a vision of Crystal Palace. Usagi and Mamoru take Chibiusa to Usagi's home. Chibiusa decides to stay at Usagi's place to keep an eye on her. When Chibiusa uses Luna-P to hypnotise Ikuko Tsukino, Kenji Tsukino, Shingo Tsukino, Usagi and Mamoru into believing she is part of the family, Luna knocks Usagi and Mamoru out of the way. Chibiusa follows Usagi everywhere.

The next day at breakfast before she goes to Rei's School fair, Usagi yells at Chibiusa not to follow her and informs Luna to keep an eye on her. While Ikuko gives Luna a saucer of milk, Chibiusa runs off to Rei's School. When she is knocked down by a sister, Rei attends to her but she gets up and runs away while watching everything that happens.

Act 16 - After Rubeus abducts Sailor Mars, Sailor Moon spots Chibiusa spying on them. Sailor Moon suspects Chibiusa is a friend of their new enemy, the Black Moon Clan. When Luna gets in the middle of Sailor Moon yelling at her, Chibiusa runs away. After Luna turns up at Mamoru's door, he follows her to a park where they find Chibiusa and bring her back to his apartment. Chibiusa sleeps in Mamoru's bed and dreams of her parents. When she wakes up crying, Mamoru cheers her up with a Tuxedo Mask puppet and a rose. Chibiusa shows her Luna-P ball to Mamoru and Luna after Luna introduces herself. Chibiusa wants to know if Sailor Moon is a good person because she believes she is the only one who can save her mother.

The next day Mamoru brings Chibiusa back to Usagi's home where Ikuko takes her inside and makes her pancakes.

Act 17 -  Chibiusa gives her Tuxedo Mask puppet to Usagi to borrow in hopes of cheering her up. Chibiusa follows Usagi to the arcade where she has gone to meet Mamoru. Chibiusa plays the Sailor V video game which alerts Minako via her Star Power Stick. Usagi, Mamoru, Makoto Kino, Minako Aino and Motoki Furuhata who are watching Chibiusa are surprised at how good she is, achieving the highest score of all time. Usagi is jealous at how good Chibiusa is at playing all the games in the arcade. Motoki gives a limited edition Sailor V doll to each Usagi and Chibiusa for being such good customers. Mamoru takes Chibiusa home while Usagi, Makoto and Minako meet Luna and Artemis at Headquarters.

While watching Ikuko and Kenji in the kitchen, Chibiusa begins to miss her parents and leaves the house. She casts a spell with the help of Luna-P to make things fun. Luna-P transforms into an umbrella which when Chibiusa open's it, birds fly out. Mamoru seeing Chibiusa on the street at night puts his hand on her shoulder and receives a vision of an entire city exploding.

Act 18 - Chibiusa brings home her new friend, Momoko after school for a play date. When Usagi, Minako, Mamoru and Luna arrive with the intention of confronting Chibiusa about her knowledge of the Black Moon, Chibiusa spots Mamoru holding the Black Crystal Earring inside a Petri dish and becomes very frightened by its presence.

Chibiusa cries in Mamoru's arms, while Minako inquires as to why she is scared of the earring. Minako gets frustrated over how uncooperative Chibiusa is being.

As Usagi sleeps Chibiusa sneaks into her room and steals the Crystal Star right off of Usagi's school uniform. When she finds Chibiusa in the park next to the fountain with her brooch, Usagi demands it back. Rubeus arrives with the intention of killing Usagi and Chibiusa when Tuxedo Mask appears and knocks down Rubeus. Usagi and Tuxedo Mask politely requests the brooch back because Usagi doesn't want to lose Sailor Venus too, she hands it over.

Chibiusa explains why she stole the Silver Crystal to Sailor Moon, Sailor Venus, Luna, Artemis and Tuxedo Mask after the battle with Calaveras. Even though she knew no matter how many Silver Crystal's she had she still wouldn't be able to use them. The past Silver Crystal only has power in the past and the future Silver Crystal only works in the future. She was taught that if the two Silver Crystal's together would be dangerous in the same time zone. But still had to try it anyway then maybe with that power she might be able to help. That's why she came to the 21st century from the 30th century. Chibiusa asks for help to save the future.

Act 19 - Chibiusa explains that she travelled through time from Crystal Tokyo in the 30th century. There was a sudden explosion then her mother wouldn't wake up. Usagi and Chibiusa stay at Mamoru's apartment overnight.

The next morning Chibiusa makes up her mind to face her fears and return to the future. At the park near the fountain, Chibiusa uses her space-time Silver Key to open a time-warp that will take Sailor Moon, Sailor Venus, Tuxedo Mask, Luna, Artemis and herself to the future. Chibiusa remembers the advise Sailor Pluto gave to her about time travel being strictly forbidden. They all hold hands as Chibiusa calls out the incantation to activate the wormhole to the future. As they begin to travel through time they let go of Chibiusa's hand.

Just as Sailor Pluto is about to destroy Sailor Moon, Sailor Venus, Tuxedo Mask, Luna and Artemis, Chibiusa intervenes, telling Sailor Pluto she is the one who brought them to the future to save her mother. When she properly introduces herself as Princess Small Lady Serenity, the team is shocked to find out that Chibiusa is a princess. Sailor Moon, Sailor Venus, Tuxedo Mask, Luna, Artemis and Chibiusa leave behind Sailor Pluto as they enter the 30th century.

Chibiusa recalls, one day there was an unbelievably big explosion that rocked the city. When the dust settled the monolith appeared and everyone except Chibiusa had collapsed. On the way to the Crystal Palace, they are stopped by Esmeraude's underlings the Boule Brothers. The Boule Brothers immobilise the team at an atomic level with their Electrochemical Side Chain. Tuxedo Mask frees them and he and Sailor Venus destroy Chiral and Achiral. Chibiusa leads the others inside the Crystal Palace to where her Mother, Neo-Queen Serenity sleeps encased within the Silver Crystal. Chibiusa is happy to see Diana alive. She sees her father.

Act 20 - When Chibiusa goes to hug her father, she passes right through him. Diana informs Chibiusa that King Endymion has been watching over her from the shadows the whole time she was in the past. Because the King is unable to protect his daughter in his current form, Chibiusa must return with the others to the future.

Sailor Moon, Sailor Venus, Tuxedo Mask, Chibiusa, Luna and Artemis travel right back to where they started in the past. Tuxedo Mask takes Chibiusa home with him because he is responsible for her and so Sailor Moon will be able to get some rest.

The next day Chibiusa turns up at the Space-Time Door alone. She enters the Palace room where the future Inner Senshi, Luna, Artemis and King Endymion sleep before visiting her mother. She cries.

Luna-P alerts Chibiusa to the presence of Esmeraude, who grabs her by the throat with her Beast Hand then Sailor Moon, Sailor Venus, Tuxedo Mask, Luna and Artemis arrive. Sailor Venus uses her Venus Love-Me Chain against Esmeraude and she drops Chibiusa who Tuxedo Mask manages to catch.

Act 21 - Chibiusa recalls when she was in the past wondering if Usagi was really her mother, Neo-Queen Serenity. Chibiusa watched Usagi with Ikuko getting a lecture on another low test score. She wants so much to be like her mother but she believes she'll never grow up to be a lady. Chibiusa lost self confidence when she was bullied by boys.

Chibiusa blames herself for everything that has happened, she used Luna-P to break the Silver Crystal out of its casing. Neo-Queen Serenity seen it was missing and went look for her daughter, when she was attacked by Prince Demande.

Once went she ran away from a group of bullies, Chibiusa went down a forbidden corridor in the very back of the Palace that's when Chibiusa found the Space-Time Door. When she went through the door she met Sailor Pluto, who taught her to cast a spell using Luna-P that will make her better whenever she is feeling down.

When Chibiusa visits Sailor Pluto who she finds her with her father. Chibiusa walks off into the space-time void alone. Luna-P alerts her to danger, Chibiusa searches for her Silver Key but is lost. Wiseman appears and temps Chibiusa with his words, until Chibiusa takes his hand.

Act 22 - Wiseman changes Chibiusa into Black Lady.

Act 25 - Black Lady memories come flooding back to her, she remembers throwing Luna-P at Sailor Pluto to distract her while Chibiusa stole a Silver Key from her chain.

When Black Lady's crystal earrings shatter and she is transformed back into Chibiusa, time resumes and she transforms for the first time into Sailor Chibi Moon.

Act 26 - Usagi awakens wondering if it was all a dream until Chibiusa pokes her head around Usagi's bedroom door and greats her good morning. On their way to where Usagi thinks is school, Chibiusa informs Usagi that she is returning to the 30th century. Usagi runs back home, Chibiusa follows and they cry. Usagi and Chibiusa return to where Chibiusa first fell from the sky near the fountain in the park. When Mamoru arrives, he gives Chibiusa his Tuxedo Mask puppet as a farewell gift. Chibiusa gives Usagi her mothers Spiral Heart Moon Rod that Neo-Queen Serenity sent to go with Usagi's new Cosmic Powers. As Chibiusa leaves she lets Usagi know that she will miss her the most.

When Usagi and Mamoru kiss, Luna-P drops from the sky and bounces onto Mamoru's head followed by Chibiusa who lands onto the back of Usagi's neck and kiss Mamoru's mouth again. Chibiusa hands a letter from Neo-Queen Serenity to Usagi stating Chibiusa is back for Sailor Guardian training.

Act 27 Part 1 - While eating breakfast with Diana, Chibiusa hears a news-report that Luna and Kenji are watching about an unidentified monster that could be a result of atavism. Chibiusa inquires to the meaning of atavism, Kenji tells her it is an evolutionary throwback. When Usagi runs off to meet Mamoru in the park, Chibiusa follows her. After giving Usagi her lunch she left at home, Chibiusa walks to school with Momoko and another friend.

Act 27 Part 2 - Chibiusa and her friends go to the new amusement park in Sankakusu with Mamoru as their chaperone. While riding the rollercoaster with Momoko, Chibiusa's hat blows off. When she chases after it, Chibiusa tells Momoko to stay behind, but she finds Mamoru that Chibiusa has left the park alone and he goes after her.

When Chibiusa finds her hat on the steps of Mugen Academy outside in the restricted area she sees Hotaru Tomoe crying. When Chibiusa asks if Hotaru is alright, she slaps her hand away and explains she gets these attacks often but it will soon pass on its own. Usagi comes across Chibiusa. Both Chibiusa's Prism Heart Compact and Usagi's Cosmic Heart Compact glow. When a Daimon attacks Usagi and Chibiusa, they scream and Ami, Rei, Makoto and Minako come running. Unbeknown to them, as all 6 transform they are watched by Sailor Neptune, Sailor Uranus and Hotaru Tomoe. For the first time Chibiusa calls out Moon Prism Power, Make Up to transform into Sailor Chibi Moon.

Act 28 - Usagi, Ami, Rei, Makoto, Minako, Mamoru and Chibiusa meet at HQ where Luna and Artemis have been analysis the two unknown Sailor Guardians. Chibiusa is wonders about Hotaru.

While at the Fruits Parlor Crown Cafe, Chibiusa tells Usagi, Ami, Makoto and Minako how she was selected to be class President of her second grade class home room and she even got to attend the entrance ceremony to welcome the new first grade students.Lilith appears to be a vaguely-formed roughly Evangelion-sized humanoid upper torso with blubbery white flesh, of non-distinct gender. Lilith has no legs or hips when it is seen in the year 2015, its torso terminating in blobby masses with dozens of humanoid-sized pairs of legs growing out of it. Lilith is kept restrained in Terminal Dogma, crucified on a giant red cross; large nails are driven through its palms into the cross from which it hangs. Lilith has five fingers on each hand (just like a human). Lilith remains totally immobile and unreactive, simply hanging limp on the cross it's nailed to and unresponsive to events around it.

The Spear of Longinus was impaled through Lilith's chest while it was restrained on the cross in Terminal Dogma, but after Eva Unit-00 removed the Lance in Episode 23, Lilith's lower legs grew back (though its new legs still had dozens of pairs of humanoid legs growing out of them, from the region of its thighs).

LCL is actually Lilith's blood, a steady stream of it pouring down the cross, and it is the true source of the LCL used in Evangelion Entry Plugs. In fact, the "LCL Production Plant" is really just a large artificial lake of LCL formed by it pooling on the level beneath Lilith's red cross. The LCL apparently flows out of the exit wound formed by the Spear of Longinus in Lilith's back (as there is no LCL flowing out of the front of its torso) though Nerv has been collecting LCL from Lilith since long before the Spear was recovered in 2015 (in Episode 12). Several production sketches reveal that there are actually tubes coming out of the back of Lilith's head, labeled "LCL tube A" etc., which may be another means of extracting it.

Perhaps Lilith's most distinctive feature is the purple mask which covers its face. Lilith has seven eyes arranged in two vertical rows on its face, three on the right and four on the left, and the mask contains holes for each of the eyes. Etched onto the mask is a pointed-downwards triangle which intersects all of the eyes (except for the lowest eye on the left). It is not entirely clear if the mask is a natural part of Lilith (some form of bone-plate), or if it is another artificial restraint placed onto it. The symbol of the mysterious Seele organization is the face of Lilith: a pointed down triangle intersecting seven eyes arranged unevenly into two rows of three and four. Whether the mask is a restraint which Seele put its emblem on, or if the mask is part of Lilith's naturally-occurring face and Seele copied it as their symbol, is unknown. The purple mask is roughly oval-shaped, and is somewhat dinged and dented.

Lilith's marshmallowy white flesh forms several blubbery folds around its head (leading to the appearance of almost having two double chins). Lilith also has two ill-defined lumpy and uneven blobs on the sides of its head which are apparently its ears. Lilith's back, visible only when it descends from its cross moments before it physically begins to manifest as Rei (when it merges with her), appears to be very bumpy where vertebrae form large blubbery lumps in a line running down its back.

Billions of years ago, Lilith's "Black Moon" transport vessel collided violently with Earth, purely by accident, in the event known as "First Impact," creating Earth's Moon. She would have had her own Spear of Longinus with her as well, but it is presumed not to have survived the crash (CI). Earth already had a Seed of Life present on it (Adam), but no two Seeds are meant to land on the same planet. However, because Lilith's Spear of Longinus had been destroyed, the only remaining Spear on the planet (Adam's) activated to try to fix the situation, and reduced Adam to a state of dormancy. Lilith then spread the primordial ooze from which "normal" terrestrial life on Earth evolved over the course of billions of years (bacteria, dolphins, monkeys, etc.), which culminated in the human race. Thus Lilith's progeny, humanity, usurped the place of Adam's progeny, the Angels, as the dominant race on Earth.

For ages, the Black Moon containing Lilith was embedded deep within the Earth, and due to shifting tectonic plates the subterranean Black Moon eventually moved to a position underneath what would become Hakone, Japan, forming the massive underground cavern termed the "Geofront."

At some undetermined point in the recent past (possibly even before Second Impact), the Black Moon and Lilith were discovered by Seele. Gehirn (later, Nerv) headquarters and Tokyo-3 were built around its position. Lilith was kept crucified on a giant cross in the deepest and most secret level of Nerv HQ, Terminal Dogma, and used as a renewable source of LCL for the Evangelion Units (LCL in fact being Lilith's blood). Seele and Nerv used Lilith for various experiments, then intentionally let Lilith grow to a point just before it could be used to initiate Instrumentality (for convenience), but then halted its growth by impaling it on the recovered Spear of Longinus which had been paired with Adam. Thus Lilith would be ready to use in initiating Third Impact as soon as the other components needed for the process were in place.

Eva-01, unlike the other Evangelion units, was created from Lilith (in End of Evangelion, it is referred to, ambiguously, as "Lilith no Bunshin"). Still images in Episode 23 suggest that instead of merely taking genetic samples from Lilith, Evangelion Unit-01 was created by physically tearing away from the lower half of Lilith, forming itself from the body mass of Lilith's legs (explaining its legs' conspicuous absence) and tearing away from Lilith trailing tattered ropes of flesh, in a mockery of the natural birth process.

In The End of Evangelion, Gendo forces his hand into Rei III, merging the Adam embryo in his right hand with her in an attempt to control Lilith and reunite with Yui. However, Rei rejects Gendo and with Adam's body and soul within her, she proceeds to merge with Lilith's body in Terminal Dogma. The gestalt Rei/Adam/Lilith being then initiates Third Impact and Instrumentality. However, Shinji Ikari ultimately chooses to reject Instrumentality, and Eva-01 bursts from the being's eye and breaks the Spear of Longinus in two. The Rei/Adam/Lilith being then falls to Earth in pieces, presumably dead.

While there is no official name for this being, it is commonly referred to in the fan community as "Giant Naked Rei" or GNR. However, it's also common to consider this being primarily Lilith. Since Rei was essentially Lilith itself, and Adam (as Kaworu) only appears briefly it seems that Lilith has primary control over the being.

Lilith appears again in Rebuild of Evangelion, although the timing and circumstances of its appearance onscreen are vastly different. While Lilith is seen in the series at the beginning of the descent arc (end of Episode 15), Lilith is seen roughly three-fourths of the way through Rebuild of Evangelion 1.0. Instead of Kaji revealing Lilith to Misato, Misato herself shows Lilith to Shinji in order to explain the urgency of fighting Ramiel, and correctly identifies Lilith as such. Dialogue between Gendo and Fuyutsuki reveals that a "contract" has been established between Seele and Lilith that involves the destruction of all the Angels, for purposes involving the Human Instrumentality Project.

Lilith is seen during the abortive Third Impact at the end of Evangelion 2.0, with what appears to be a faint glow and small white sparks floating off her body. Keel Lorenz, in an earlier conversation with Gendo, speaks about "resurrecting" Lilith. It is heavily implied that Lilith was in some way affected by the events surrounding Eva-01 at the end of Evangelion 2.0, though to what extent is at present unknown. It is also unknown what was done to Lilith during the 14-year time period between the setting of the two movies.

In Evangelion 3.0, Lilith has been effectively split into two: her head, having taken the shape of Rei's head, is in the old Nerv Command Center surrounded by Failures of Infinity that are reaching out to it. Deep within her original chamber, Lilith's body has pulled off the cross and grown to many times her original size. Eva-06 is fused to where the neck should be and has briefly grown with Lilith before impaling her with two Spears. The body is decaying and in poor condition, with the same red grid pattern seen on the Moon's surface and in Eva-01's old cage. Her body explodes into red fluid when Shinji in Eva-13 removes the Spears, forming around the 12th Angel as an initiator of Fourth Impact.

Lilith's design in Rebuild had undergone an overhaul as well. No longer does Lilith have its trademark seven-eyed mask, but instead has an ossified mask or faceplate similar to the face Sachiel grows after the N2 mine attack, with two eyeholes and a small beak protruding out of the lower end of the mask.

The Spear of Longinus is already impaled through its chest and the large bolts driven through its palms and into the cross remain. However, Lilith's chest bears a large scar across it, one that resembles the scar seen on Misato's chest in the TV series in both location and appearance. In addition, a series of small cross-shaped objects are driven into its chest. Lilith's clusters of legs now twitch and sway, and it continues to trickle LCL into the lake below.
    """
    
    top_words = find_top_words_with_entropy(corpus)
    
    print("Top 100 words with highest Shannon entropy values:")
    for word, entropy in top_words:
        print("Word:", word, "| Shannon Entropy:", entropy)

if __name__ == "__main__":
    main()
